### ISSUE TITLE
win10  miniconda  Python 3.8 词性标注报错

### ISSUE THREAD

**Issue by l99500** [dongrixinyu/jiojio#5]
Traceback (most recent call last):
  File "*/main.py", line 4, in <module>
    words_tags = jiojio.cut('致我们终将逝去的青春。')
  File "*\miniconda\envs\nlp_preprocess\lib\site-packages\jiojio\__init__.py", line 193, in cut
    words, norm_words, word_pos_map = jiojio_cws_obj.cut_with_pos(text)
  File "*\miniconda\envs\nlp_preprocess\lib\site-packages\jiojio\cws\predict_text.py", line 366, in cut_with_pos
    tags = self._cut_py(norm_segment)
UnboundLocalError: local variable 'norm_segment' referenced before assignment

**Comment by l99500** [comment]
jiojio             1.2.3
jionlp             1.4.25

**Comment by dongrixinyu** [comment]
是怎么初始化的呢？

**Comment by l99500** [comment]
> 是怎么初始化的呢？
使用的是词性标注示例代码
```
import jiojio

jiojio.init(pos=True)
words_tags = jiojio.cut('致我们终将逝去的青春。')
print([item[0] + '/' + item[1] for item in words_tags])
```
环境如下：
charset-normalizer==2.1.1
idna==3.4
jiojio==1.2.3
jionlp==1.4.25
numpy==1.23.5
PyYAML==6.0
requests==2.28.1
urllib3==1.26.13
wincertstore==0.2
zipfile36==0.1.3

**Comment by dongrixinyu** [comment]
感谢反馈是个bug，这两天会上到pypi 里
